### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by deizel** [nilportugues/sitemap#19]
I modified the [Build a simple sitemap](https://github.com/sonrisa/sitemap-component#43---build-a-simple-sitemap) example to do 50k iterations to test the feature where sitemaps split into separate files based on Google recommendations:

https://gist.github.com/deizel/373366bb1fe16149fa7c/a95eebdd6841dc618c7005435a2cee4576679cf4

However, the speed of the script quickly diminishes as each iteration is slower than the last one. My VM's CPU was pegged for almost an hour before I decided to stop the script. By comparison, another less featureful package ([evert/sitemap-php](https://github.com/evert/sitemap-php)) handled this test in under a minute on the same VM.

This looks like a great package, but I'm wondering if improvements can be made such that the sitemap generation happens in linear time. I noticed the code performs duplicate checking so having an option to disable that, instead writing items directly to disk as they are added, might improve things?

**Comment by deizel** [comment]
Nice, thanks for taking the time to look into this!

I can confirm the previous script only takes ~20 seconds now! :racehorse: :dash: 

(Modified gist for 3.x https://gist.github.com/deizel/373366bb1fe16149fa7c)

**Comment by nilopc** [comment]
Yup, actually I used your code to build the tests... so edge-cases are now actually unit tested, for all types of sitemap. 

Great, right? :)

**Comment by deizel** [comment]
Ah cool, I see it moved from e622a7920898dade8c63cc3151497ce8d7667493 to the `itShouldCreateTwoSiteMapFiles` tests.. that should help catch any performance regressions going forward too :+1:

Pretty thorough test coverage too! :smile: (might want to kick coveralls, the old build has some broken links due to the namespace changes).
